### ISSUE TITLE
Remix v2 error when deploying to vercel

### ISSUE THREAD

**Issue by Nedi11** [vercel/remix#55]
Deployment is successful but serverless functions don't work.

![image](https://github.com/vercel/remix/assets/91092824/8e1e56fd-8be7-4990-80b3-01e82bfa97fb)

I get this error:
```file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:2
  AbortController as NodeAbortController,
  ^^^^^^^^^^^^^^^
SyntaxError: Named export 'AbortController' not found. The requested module '@remix-run/node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@remix-run/node';

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
Error: Runtime exited with error: exit status 1
Runtime.ExitError```

**Comment by stormynight9** [comment]
Any updates on this?

**Comment by Sandy-Garrido** [comment]
This is a duplicate of https://github.com/vercel/remix/issues/53

**Comment by Nedi11** [comment]
This has been fixed

**Comment by reisr3** [comment]
I'm still getting this error in Vercel after upgrading everything Remix-related to v2.

I've followed the V1 to V2 guide and I'm using "@vercel/remix": "^2.0.1".

Tried both `serverModuleFormat: 'esm'` and `serverModuleFormat: 'cjs'`. Although the guide mentions this error, it just says to check the section on serverModuleFormat.

Does `@vercel/remix` v2.0.1 definitely resolve this issue for others?

**Comment by Nedi11** [comment]
> I'm still getting this error in Vercel after upgrading everything Remix-related to v2.
> 
> I've followed the V1 to V2 guide and I'm using "@vercel/remix": "^2.0.1".
> 
> Tried both `serverModuleFormat: 'esm'` and `serverModuleFormat: 'cjs'`. Although the guide mentions this error, it just says to check the section on serverModuleFormat.
> 
> Does `@vercel/remix` v2.0.1 definitely resolve this issue for others?

For me it was fixed when I updated to 2.0.0 but then another error happend on 2.0.1 so I ditched vercel completely and deployed on a server

**Comment by reisr3** [comment]
I guess I'll just back down to v1 until the ESM issues get smoothed out.

I'm not ready to ditch Vercel, but it is very frustrating when there's a compatibility issue between Remix and Vercel. I happily pay Vercel because they make everything so easy. This kind of thing detracts from that sentiment.
